### ISSUE TITLE
error comes up when running the script, "[: unexpected operator"

### ISSUE THREAD

**Issue by justvipul** [HRKings/pokemonsay-newgenerations#1]
![image](https://i.imgur.com/IIPUfp1.png)
this is the exact error

**Comment by justvipul** [comment]
heres a quick fix i found out.
line 135,
>-`if [ "${DISABLE_WRAP}" == "YES" ]; then`
>+`if [ "${DISABLE_WRAP}" = "YES" ]; then`

should i create a PR? or you can fix it?

**Comment by HRKings** [comment]
Thanks for the heads up ! I'm pushing a new version
